on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-20.04 
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19.x

      - name: Install Ionic
        run: npm install -g @ionic/cli

      - name: Install app dependencies
        working-directory: ./frontend
        run: npm ci && npm install @capacitor/cli

      - name: Build Ionic App
        working-directory: ./frontend
        env:
          CI: false
        run: ionic build

      - name: Copy Android
        working-directory: ./frontend
        env:
          CI: false
        run: ionic capacitor copy android

      - name: Build Android  APK
        working-directory: ./frontend
        env:
          CI: false
        run: ionic capacitor build android --release --prod

      - name: Generate the Android App Bundle
        working-directory: ./frontend/android/
        run: ./gradlew bundle

      - name: Upload release bundle
        uses: actions/upload-artifact@v1
        with:
          name: app-release
          path: apk/app.aab
