on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-20.04 
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 11 

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19.x

      - name: Install Ionic
        run: npm install -g @ionic/cli

      - name: Install app dependencies
        working-directory: ./frontend
        run: npm ci && npm install @capacitor/cli

      - name: Build Ionic App
        working-directory: ./frontend
        env:
          CI: false
        run: ionic build

      - name: Copy Android
        working-directory: ./frontend
        env:
          CI: false
        run: ionic capacitor copy android

      - name: Build Android  APK
        working-directory: ./frontend
        env:
          CI: false
        run: ionic capacitor build android --release --prod

      - name: Upload relese apk 
        uses: actions/upload-artifact@v3
        with:
          name: citrus
          path: ./frontend/android/app/build/outputs/apk/release/app-release-unsigned.apk
  release:
      name: Release APK
      needs: build 
      runs-on: ubuntu-latest
      steps:
      - name: Download APK from build
        uses: actions/download-artifact@v3
        with:
          name: apk  
      - name: Create Release
        id: create_release
        uses: actions/create-release@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }} 
      - name: Upload Release APK
        id: upload_release_asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: apk/app-release-unsigned.apk
          asset_name: Citrus.apk
          asset_content_type: application/zip  
