name: Citrus Continuous Integration

on:
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install Ionic CLI
      run: npm install -g ionic

    - name: Change working directory 
      run: cd frontend

    - name: Install dependencies
      run: npm ci

    - name: Build for production
      run: ionic build --prod

    - name: Lint
      run: npx tslint --project tsconfig.json






